name: Build Windows Custom Client

on:
  workflow_dispatch:

env:
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
  FLUTTER_VERSION: "3.27.4"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.3"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          runVcpkgInstall: true
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Setup environment
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $env:GITHUB_ENV

      - name: Install flutter_rust_bridge
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1 --features uuid

      - name: Build with build.py
        shell: pwsh
        run: |
          flutter config --enable-windows-desktop
          python build.py --flutter --hwcodec

      - name: Upload Release folder
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ env.VERSION }}-windows-x64
          path: flutter/build/windows/x64/runner/Release/
